name: Auto Enable Auto-merge
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'dev-be'
    steps:
      - name: Enable auto-merge
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.pulls.enableAutoMerge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.event.pull_request.number,
                merge_method: 'squash'
              });
              console.log('Auto-merge enabled successfully');
            } catch (error) {
              console.log('Failed to enable auto-merge:', error.message);
            }