name: Auto Merge (3+ approvals, dev-be only)

on:
  pull_request_review:
    types: [submitted]

jobs:
  automerge:
    if: github.event.review.state == 'approved' && github.base_ref == 'dev-be'
    runs-on: ubuntu-latest

    steps:
      - name: Auto merge when 3+ approvals
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mergeMethod: squash
          requiredApprovals: 3
          authorAssociation: "MEMBER,OWNER,COLLABORATOR"
