name: Lint-dev-be-PR

on:
  pull_request:
    branches: [ dev-be ]      # ⬅️ base 브랜치가 dev-be인 PR 한정

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      # ───── Flake8 (스타일 게이트) ─────
      - name: Run flake8
        run: |
          pip install flake8
          flake8 backend              # 필요한 경로만

      # ───── Pylint (심층 분석) ─────
      - name: Run pylint
        run: |
          pip install pylint
          pylint --fail-under=8 backend

