name: Lint (dev-be only PR)
on:
  pull_request:
    branches: [ dev-be ]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 1) pylint 설치
      - name: Install pylint
        run: |
          pip install pylint

      # 2) pylint 실행 (fail < 8/10)
      - name: Run pylint
        run: |
          pylint backend \
            --disable=missing-module-docstring,missing-function-docstring,import-error,broad-exception-caught \
            --fail-under=8
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: pip install -r requirements.txt pytest pytest-cov
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest \
            --ignore=backend/test/test_api.py \
            --ignore=backend/test/test_gemini.py \
            --cov=backend --cov-fail-under=80