# .github/workflows/lint.yml
name: Lint (dev-be only PR)

on:
  pull_request:
    branches: [ dev-be ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5        # ① cache 옵션 제거
        with:
          python-version: "3.10"

      - name: Install flake8 & pylint        # ② 필요한 패키지 수동 설치
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint

      - name: Run flake8
        run: flake8 .

      - name: Run pylint
        run: pylint --fail-under=8 .
