name: Lint-dev-be-PR

on:
  pull_request:
    branches: [ dev-be ]      # ⬅️ base 브랜치가 dev-be인 PR 한정

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"         # 필요한 경로만

      # ───── Pylint (심층 분석) ─────
      - name: Run pylint
        run: |
          pylint backend \
            --disable=missing-module-docstring,missing-function-docstring,import-error,broad-exception-caught \
            --fail-under=8

